### PR TITLE
Fix/docker

### PR DESCRIPTION
**Pull request by omareloui**
## Docker and docker-compose:
- Fix issues with Dockerfile (include the source code to build from it).
- Remove the version from `docker-compose` files as they are deprecated.
- Improve the image size: reduce from 700+ MB to 400+ MB.
- Run the script with a different user other than the default one of the images.
- Add `pgadmin` to `docker-compose` file as option to run if needed.

## Documentation:
- Update the `README.md` to reflect the changes.
- Add a note over populating the database.
- Format the `README.md` file and add missing code block language.
- Replace the command `docker-compose` with `docker compose` as this is what the newer version of docker uses.

---

- Include package-lock.json.

### CODE REVIEW

**Comment by gvelez17** [comment]
@omareloui do we still need this?  if not lets close and clean up, PRs should always be reviewed within 1-2 days if possible, ping noisily if not

**Comment by omareloui** [comment]
I think it's outdated now. It fixes a lot of stuff with docker and makes it way easier to run locally and on servers if we needed to use docker.

I have this running on my local env on the parent dir. I thought sharing it will help anyone who might need to run DB, microservice, and the backend on their local device to make it easier to develop without missing with any dev data

**Comment by omareloui** [comment]
If that's something that could be used, I'll update it and notify whoever can test it

**Review by gvelez17 — APPROVED** [review]
ok, this is for development only so just report if anything is not working

**Pull request merged**
